dist: trusty
sudo: false
language: c
env:
  matrix:
    - VALGRIND=On SANITIZERS=Off
    - VALGRIND=Off SANITIZERS=Off
    - VALGRIND=Off SANITIZERS=On
compiler:
  - gcc
  - clang
addons:
  apt:
    packages:
      - valgrind
      - libasan0
      - lib32asan0
      # currently not supported on travis:
      # - libasan1
      # - libasan2
      # - libubsan0
      - llvm
script:
  - mkdir build
  - cd build
  - cmake .. -DENABLE_CJSON_UTILS=On -DENABLE_VALGRIND="${VALGRIND}" -DENABLE_SAFE_STACK="${VALGRIND}"  -DENABLE_SANITIZERS="${SANITIZERS}"
  - make
  - make test CTEST_OUTPUT_ON_FAILURE=On
notifications:
  #email:
  #- qpalzmm22@gmail.com
    #notifications:
  slack:
    rooms:
      - 'handong-crew:n9k0NIiPB6e5Alzs33VhZ6MI#travis-practice'
    template:
    - "Build <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}>) of %{repository_slug}@%{branch} by %{author} %{result} in %{duration}"
    on_success: never
    on_failure: always
